name: Benchmark LEVM vs REVM

on:
  pull_request:
    branches: ["**"]
    paths:
      - "crates/vm/levm/**"
      - ".github/workflows/pr_perf_levm.yaml"

permissions:
  pull-requests: write

jobs:
  benchmark-pr:
    name: Benchmark for PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.81.0
        with:
          toolchain: ${{ vars.RUST_VERSION }}
          components: rustfmt, clippy

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Install hyperfine
        uses: taiki-e/install-action@v2
        with:
          tool: hyperfine@1.16

      - name: Install solc
        uses: pontem-network/get-solc@master
        with:
          version: v0.8.29

      - name: Run PR benchmarks
        run: |
          cd crates/vm/levm
          make revm-comparison-ci
          {
            echo "#### Benchmark Results: Factorial";
            cat Factorial.md || echo "No results";
            echo "#### Benchmark Results: Factorial - Recursive";
            cat FactorialRecursive.md || echo "No results";
            echo "#### Benchmark Results: Fibonacci";
            cat Fibonacci.md || echo "No results";
            echo "#### Benchmark Results: ManyHashes";
            cat ManyHashes.md || echo "No results";
            echo "#### Benchmark Results: BubbleSort";
            cat BubbleSort.md || echo "No results";
            echo "#### Benchmark Results: ERC20 - Transfer";
            cat ERC20Transfer.md || echo "No results";
            echo "#### Benchmark Results: ERC20 - Mint";
            cat ERC20Mint.md || echo "No results";
            echo "#### Benchmark Results: ERC20 - Approval";
            cat ERC20Approval.md || echo "No results";
          } > pr_result.md

      - name: Upload PR results
        uses: actions/upload-artifact@v4
        with:
          name: pr-result
          path: crates/vm/levm/pr_result.md

  benchmark-main:
    name: Benchmark for Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.81.0
        with:
          toolchain: ${{ vars.RUST_VERSION }}
          components: rustfmt, clippy

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Install hyperfine
        uses: taiki-e/install-action@v2
        with:
          tool: hyperfine@1.16

      - name: Install solc
        uses: pontem-network/get-solc@master
        with:
          version: v0.8.29

      - name: Run main benchmarks
        run: |
          cd crates/vm/levm
          make revm-comparison-ci
          {
            echo "#### Benchmark Results: Factorial";
            cat Factorial.md || echo "No results";
            echo "#### Benchmark Results: Factorial - Recursive";
            cat FactorialRecursive.md || echo "No results";
            echo "#### Benchmark Results: Fibonacci";
            cat Fibonacci.md || echo "No results";
            echo "#### Benchmark Results: ManyHashes";
            cat ManyHashes.md || echo "No results";
            echo "#### Benchmark Results: BubbleSort";
            cat BubbleSort.md || echo "No results";
            echo "#### Benchmark Results: ERC20 - Transfer";
            cat ERC20Transfer.md || echo "No results";
            echo "#### Benchmark Results: ERC20 - Mint";
            cat ERC20Mint.md || echo "No results";
            echo "#### Benchmark Results: ERC20 - Approval";
            cat ERC20Approval.md || echo "No results";
          } > main_result.md

      - name: Upload main results
        uses: actions/upload-artifact@v4
        with:
          name: main-result
          path: crates/vm/levm/main_result.md

  combine-results:
    name: Combine Benchmark Results
    runs-on: ubuntu-latest
    needs: [benchmark-pr, benchmark-main]
    steps:
      - name: Download PR results
        uses: actions/download-artifact@v4
        with:
          name: pr-result
          path: .

      - name: Download main results
        uses: actions/download-artifact@v4
        with:
          name: main-result
          path: .

      - name: Create combined results
        run: |
          {
            echo "# Benchmark Results Comparison";
            echo "## PR Results";
            cat pr_result.md;
            echo "## Main Results";
            cat main_result.md;
          } > combined_result.md

      - name: Find comment
        continue-on-error: true
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "Benchmark Results Comparison"

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: combined_result.md
          edit-mode: replace
